/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "primary-container": "#063b5c",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#a2cbf3",
        "on-secondary-container": "#005b78",
        "inverse-surface": "#133346",
        "outline-variant": "#c2c7ce",
        "on-surface-variant": "#42474e",
        "tertiary-fixed-dim": "#4fd7f0",
        "error": "#ba1a1a",
        "surface": "#f6faff",
        "on-secondary-fixed": "#001e2b",
        "tertiary-fixed": "#a3eeff",
        "surface-container-low": "#eaf5ff",
        "inverse-primary": "#a2cbf3",
        "outline": "#72787e",
        "on-tertiary-fixed-variant": "#004e5a",
        "on-tertiary-container": "#00b1c9",
        "tertiary": "#00272d",
        "surface-bright": "#f6faff",
        "secondary-container": "#7cd4fe",
        "on-background": "#001e2e",
        "on-primary-container": "#7da5cc",
        "primary": "#00253d",
        "surface-container-highest": "#c7e7fe",
        "surface-variant": "#c7e7fe",
        "tertiary-container": "#003e47",
        "on-tertiary": "#ffffff",
        "background": "#f6faff",
        "secondary-fixed-dim": "#79d1fb",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#e4f3ff",
        "on-secondary": "#ffffff",
        "surface-dim": "#bfdef6",
        "on-primary-fixed": "#001d32",
        "primary-fixed": "#cde5ff",
        "on-secondary-fixed-variant": "#004d66",
        "surface-tint": "#386285",
        "secondary-fixed": "#c0e8ff",
        "on-tertiary-fixed": "#001f25",
        "on-primary-fixed-variant": "#1d4a6c",
        "on-surface": "#001e2e",
        "secondary": "#006686",
        "surface-container-high": "#d3ebff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#dff0ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "margin-desktop": "2rem",
        "space-md": "0.75rem",
        "space-2xs": "0.125rem",
        "space-3xl": "3rem",
        "space-2xl": "2rem",
        "space-sm": "0.5rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter-compact": "0.75rem",
        "gutter-default": "1.25rem",
      },
      fontFamily: {
        "caption-coordinate": ["Geist", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-technical": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "data-metric": ["Geist", "sans-serif"],
      },
      fontSize: {
        "caption-coordinate": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-technical": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" }],
        "display": ["44px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-sm": ["17px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "data-metric": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
